version: '3'

#
# Have a look at the .env file -> used for configuration
#

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    init: true
    expose:
      - "15672"
      - "5672"
    hostname: ataka-rabbitmq
    networks:
      - ataka
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ${DATA_STORE}/rabbitmq:/var/lib/rabbitmq:rw

  postgres:
    image: postgres:14-alpine
    restart: always
    init: true
    hostname: ataka-postgres
    networks:
      - ataka
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_STORE}/postgres:/var/lib/postgresql/data:rw

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "${BIND_ADDRESS}:8080:8080"
    hostname: ataka-adminer
    networks:
      - ataka
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  api:
    image: openattackdefensetools/ataka-api
    restart: always
    init: true
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/api/Dockerfile
    volumes:
      - ${DATA_STORE}/shared:/data/shared:rw,z
      - ${DATA_STORE}/exploits:/data/exploits:rw,z
    ports:
      - "${BIND_ADDRESS}:8000:8000"
    security_opt:
      - label:disable
    depends_on:
      - postgres
      - rabbitmq
    hostname: ataka-api
    networks:
      - ataka
    env_file:
      - .env

  executor:
    image: openattackdefensetools/ataka-executor
    restart: always
    init: true
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/executor/Dockerfile
    volumes:
      - /var/run/docker.sock:/run/docker.sock:rw
      - ${DATA_STORE}/shared:/data/shared:rw,z
      - ${DATA_STORE}/exploits:/data/exploits:rw,z
      - ${DATA_STORE}/persist:/data/persist:rw,z
    security_opt:
      - label:disable
    depends_on:
      - postgres
      - rabbitmq
    hostname: ataka-executor
    networks:
      - ataka
    env_file:
      - .env

  exploit:
    image: alpine:latest
    command: "sleep infinity"
    restart: always
    init: true
    user: $USERID
    container_name: ataka-exploit
    networks:
      - ataka-exploits

  # Valkey server for CTF code and exploits
  # not currently used by ataka but useful for complex exploits and ctfconfigs 
  valkey:
    image: valkey/valkey:latest
    container_name: valkey-server
    environment:
      - VALKEY_EXTRA_FLAGS=--bind 0.0.0.0 --dir /data --appendonly no --save 900 1 --save 300 10 --save 60 10000
    ports:
      - "${BIND_ADDRESS}:6379:6379"
    volumes:
      - ${DATA_STORE}/valkey:/data
    command: ["valkey-server"]
    restart: unless-stopped
    networks:
      - ataka
      - ataka-exploits

  ctfcode:
    image: openattackdefensetools/ataka-ctfcode
    restart: always
    init: true
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/ctfcode/Dockerfile
    volumes:
      - ./ataka/ctfconfig:/ataka/ctfconfig:ro
      - ./ataka/player-cli:/ataka/player-cli:ro
      - ${DATA_STORE}/shared:/data/shared:rw,z
    security_opt:
      - label:disable
    depends_on:
      - postgres
      - rabbitmq
    hostname: ataka-ctfcode
    networks:
      - ataka
    env_file:
      - .env

  cli:
    image: openattackdefensetools/ataka-cli
    restart: always
    init: true
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/cli/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    hostname: ataka-cli
    networks:
      - ataka
    env_file:
      - .env

networks:
  ataka:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-ataka
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112

  ataka-exploits:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-exploits
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB9::/112
